// =============================================================================
// Copyright Raspberry Pi (Trading) Ltd. 2021
// vrbuild version: 9538f40556556aecde1b62d51c7212d19d4de71b-clean
// THIS FILE IS GENERATED BY VRBUILD - DO NOT EDIT
// =============================================================================
// Register block : AUDIO_OUT
// Version        : 1
// Bus type       : apb
// Description    : Control and status registers for audio_out peripheral
//                  Writes to these registers are synchronised into the
//                  pwm_audio clock domain.
//                  It will take 2 pwm_audio sample clocks for the register
//                  write to take effect.
// =============================================================================
#ifndef AUDIO_OUT_REGS_DEFINED
#define AUDIO_OUT_REGS_DEFINED
#define AUDIO_OUT_REGS_RWTYPE_MSB 13
#define AUDIO_OUT_REGS_RWTYPE_LSB 12
// =============================================================================
// Register    : AUDIO_OUT_CTRL
// JTAG access : synchronous
// Description : Base control register for peripheral
#define AUDIO_OUT_CTRL_OFFSET 0x00000000
#define AUDIO_OUT_CTRL_BITS   0x80000f07
#define AUDIO_OUT_CTRL_RESET  0x00000a00
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_CTRL_PERIPH_EN
// Description : 1 - Enable audio output peripheral
//               0 - Disable audio output peripheral
//               Note: This bit must be written to a 1 separately from all other
//               bits
//               in this register in order to guarantee sample synchronisation.
#define AUDIO_OUT_CTRL_PERIPH_EN_RESET  0x0
#define AUDIO_OUT_CTRL_PERIPH_EN_BITS   0x80000000
#define AUDIO_OUT_CTRL_PERIPH_EN_MSB    31
#define AUDIO_OUT_CTRL_PERIPH_EN_LSB    31
#define AUDIO_OUT_CTRL_PERIPH_EN_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_CTRL_CIC_RATE
// Description : Adjust the CIC filter rate. Note: changing this will likely
//               cause undesirable interactions with the CIC compensation filter
//               passband-edge.
#define AUDIO_OUT_CTRL_CIC_RATE_RESET  0xa
#define AUDIO_OUT_CTRL_CIC_RATE_BITS   0x00000f00
#define AUDIO_OUT_CTRL_CIC_RATE_MSB    11
#define AUDIO_OUT_CTRL_CIC_RATE_LSB    8
#define AUDIO_OUT_CTRL_CIC_RATE_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_CTRL_CHANNEL_SWAP
// Description : 1 - Swap the sense of left/right on output pins
//               0 - Don't swap channels over
#define AUDIO_OUT_CTRL_CHANNEL_SWAP_RESET  0x0
#define AUDIO_OUT_CTRL_CHANNEL_SWAP_BITS   0x00000004
#define AUDIO_OUT_CTRL_CHANNEL_SWAP_MSB    2
#define AUDIO_OUT_CTRL_CHANNEL_SWAP_LSB    2
#define AUDIO_OUT_CTRL_CHANNEL_SWAP_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_CTRL_RIGHT_CH_ENABLE
// Description : Right PWM engine control
//               1 - Enable right channel
//               0 - Disable right channel
#define AUDIO_OUT_CTRL_RIGHT_CH_ENABLE_RESET  0x0
#define AUDIO_OUT_CTRL_RIGHT_CH_ENABLE_BITS   0x00000002
#define AUDIO_OUT_CTRL_RIGHT_CH_ENABLE_MSB    1
#define AUDIO_OUT_CTRL_RIGHT_CH_ENABLE_LSB    1
#define AUDIO_OUT_CTRL_RIGHT_CH_ENABLE_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_CTRL_LEFT_CH_ENABLE
// Description : Left PWM engine control
//               1 - Enable left channel
//               0 - Disable left channel
#define AUDIO_OUT_CTRL_LEFT_CH_ENABLE_RESET  0x0
#define AUDIO_OUT_CTRL_LEFT_CH_ENABLE_BITS   0x00000001
#define AUDIO_OUT_CTRL_LEFT_CH_ENABLE_MSB    0
#define AUDIO_OUT_CTRL_LEFT_CH_ENABLE_LSB    0
#define AUDIO_OUT_CTRL_LEFT_CH_ENABLE_ACCESS "RW"
// =============================================================================
// Register    : AUDIO_OUT_SDMCTL_LEFT
// JTAG access : synchronous
// Description : Left channel sigma-delta modulation control
#define AUDIO_OUT_SDMCTL_LEFT_OFFSET 0x00000004
#define AUDIO_OUT_SDMCTL_LEFT_BITS   0xffff00ff
#define AUDIO_OUT_SDMCTL_LEFT_RESET  0x00000000
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_SDMCTL_LEFT_BIAS
// Description : Unsigned offset to be added to output PWM code when not
//               muting/unmuting
//               Set to PWM_RANGE / 2 in normal operation
#define AUDIO_OUT_SDMCTL_LEFT_BIAS_RESET  0x0000
#define AUDIO_OUT_SDMCTL_LEFT_BIAS_BITS   0xffff0000
#define AUDIO_OUT_SDMCTL_LEFT_BIAS_MSB    31
#define AUDIO_OUT_SDMCTL_LEFT_BIAS_LSB    16
#define AUDIO_OUT_SDMCTL_LEFT_BIAS_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_SDMCTL_LEFT_BYPASS
// Description : 1 - Bypass the sigma-delta modulator
//               0 - Apply quantisation and/or noise shaping
#define AUDIO_OUT_SDMCTL_LEFT_BYPASS_RESET  0x0
#define AUDIO_OUT_SDMCTL_LEFT_BYPASS_BITS   0x00000080
#define AUDIO_OUT_SDMCTL_LEFT_BYPASS_MSB    7
#define AUDIO_OUT_SDMCTL_LEFT_BYPASS_LSB    7
#define AUDIO_OUT_SDMCTL_LEFT_BYPASS_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_SDMCTL_LEFT_SDM_ORDER
// Description : Select noise shaping loop order
//               0 - Second-order noise shaping
//               1 - Flat quantisation
#define AUDIO_OUT_SDMCTL_LEFT_SDM_ORDER_RESET  0x0
#define AUDIO_OUT_SDMCTL_LEFT_SDM_ORDER_BITS   0x00000040
#define AUDIO_OUT_SDMCTL_LEFT_SDM_ORDER_MSB    6
#define AUDIO_OUT_SDMCTL_LEFT_SDM_ORDER_LSB    6
#define AUDIO_OUT_SDMCTL_LEFT_SDM_ORDER_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_SDMCTL_LEFT_CLAMP_EN
// Description : 1 - Apply pre-quantisation clamping for non-pow2 PWM ranges
//               0 - Quantiser input is the full s16 range
#define AUDIO_OUT_SDMCTL_LEFT_CLAMP_EN_RESET  0x0
#define AUDIO_OUT_SDMCTL_LEFT_CLAMP_EN_BITS   0x00000020
#define AUDIO_OUT_SDMCTL_LEFT_CLAMP_EN_MSB    5
#define AUDIO_OUT_SDMCTL_LEFT_CLAMP_EN_LSB    5
#define AUDIO_OUT_SDMCTL_LEFT_CLAMP_EN_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_SDMCTL_LEFT_DITHER_EN
// Description : 1 - Apply PRNG 1-bit dither immediately before quantiser input
//               0 - Disable sample dithering
#define AUDIO_OUT_SDMCTL_LEFT_DITHER_EN_RESET  0x0
#define AUDIO_OUT_SDMCTL_LEFT_DITHER_EN_BITS   0x00000010
#define AUDIO_OUT_SDMCTL_LEFT_DITHER_EN_MSB    4
#define AUDIO_OUT_SDMCTL_LEFT_DITHER_EN_LSB    4
#define AUDIO_OUT_SDMCTL_LEFT_DITHER_EN_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_SDMCTL_LEFT_OUTPUT_BITWIDTH
// Description : 0-15: Set quantiser bitwidth - 1
//               i.e. bitwidth = 0 => quantise to 1-bit output.
#define AUDIO_OUT_SDMCTL_LEFT_OUTPUT_BITWIDTH_RESET  0x0
#define AUDIO_OUT_SDMCTL_LEFT_OUTPUT_BITWIDTH_BITS   0x0000000f
#define AUDIO_OUT_SDMCTL_LEFT_OUTPUT_BITWIDTH_MSB    3
#define AUDIO_OUT_SDMCTL_LEFT_OUTPUT_BITWIDTH_LSB    0
#define AUDIO_OUT_SDMCTL_LEFT_OUTPUT_BITWIDTH_ACCESS "RW"
// =============================================================================
// Register    : AUDIO_OUT_SDMCTL_RIGHT
// JTAG access : synchronous
// Description : Right channel sigma-delta modulation control
#define AUDIO_OUT_SDMCTL_RIGHT_OFFSET 0x00000008
#define AUDIO_OUT_SDMCTL_RIGHT_BITS   0xffff00ff
#define AUDIO_OUT_SDMCTL_RIGHT_RESET  0x00000000
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_SDMCTL_RIGHT_BIAS
// Description : Unsigned offset to be added to output PWM code when not
//               muting/unmuting
//               Set to PWM_RANGE / 2 in normal operation
#define AUDIO_OUT_SDMCTL_RIGHT_BIAS_RESET  0x0000
#define AUDIO_OUT_SDMCTL_RIGHT_BIAS_BITS   0xffff0000
#define AUDIO_OUT_SDMCTL_RIGHT_BIAS_MSB    31
#define AUDIO_OUT_SDMCTL_RIGHT_BIAS_LSB    16
#define AUDIO_OUT_SDMCTL_RIGHT_BIAS_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_SDMCTL_RIGHT_BYPASS
// Description : 1 - Bypass the sigma-delta modulator
//               0 - Apply quantisation and/or noise shaping
#define AUDIO_OUT_SDMCTL_RIGHT_BYPASS_RESET  0x0
#define AUDIO_OUT_SDMCTL_RIGHT_BYPASS_BITS   0x00000080
#define AUDIO_OUT_SDMCTL_RIGHT_BYPASS_MSB    7
#define AUDIO_OUT_SDMCTL_RIGHT_BYPASS_LSB    7
#define AUDIO_OUT_SDMCTL_RIGHT_BYPASS_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_SDMCTL_RIGHT_SDM_ORDER
// Description : Select noise shaping loop order
//               0 - Second-order noise shaping
//               1 - Flat quantisation
#define AUDIO_OUT_SDMCTL_RIGHT_SDM_ORDER_RESET  0x0
#define AUDIO_OUT_SDMCTL_RIGHT_SDM_ORDER_BITS   0x00000040
#define AUDIO_OUT_SDMCTL_RIGHT_SDM_ORDER_MSB    6
#define AUDIO_OUT_SDMCTL_RIGHT_SDM_ORDER_LSB    6
#define AUDIO_OUT_SDMCTL_RIGHT_SDM_ORDER_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_SDMCTL_RIGHT_CLAMP_EN
// Description : 1 - Apply pre-quantisation clamping for non-pow2 PWM ranges
//               0 - Quantiser input is the full s16 range
#define AUDIO_OUT_SDMCTL_RIGHT_CLAMP_EN_RESET  0x0
#define AUDIO_OUT_SDMCTL_RIGHT_CLAMP_EN_BITS   0x00000020
#define AUDIO_OUT_SDMCTL_RIGHT_CLAMP_EN_MSB    5
#define AUDIO_OUT_SDMCTL_RIGHT_CLAMP_EN_LSB    5
#define AUDIO_OUT_SDMCTL_RIGHT_CLAMP_EN_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_SDMCTL_RIGHT_DITHER_EN
// Description : 1 - Apply PRNG 1-bit dither immediately before quantiser input
//               0 - Disable sample dithering
#define AUDIO_OUT_SDMCTL_RIGHT_DITHER_EN_RESET  0x0
#define AUDIO_OUT_SDMCTL_RIGHT_DITHER_EN_BITS   0x00000010
#define AUDIO_OUT_SDMCTL_RIGHT_DITHER_EN_MSB    4
#define AUDIO_OUT_SDMCTL_RIGHT_DITHER_EN_LSB    4
#define AUDIO_OUT_SDMCTL_RIGHT_DITHER_EN_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_SDMCTL_RIGHT_OUTPUT_BITWIDTH
// Description : 0-15: Set quantiser bitwidth - 1
//               i.e. bitwidth = 0 => quantise to 1-bit output.
#define AUDIO_OUT_SDMCTL_RIGHT_OUTPUT_BITWIDTH_RESET  0x0
#define AUDIO_OUT_SDMCTL_RIGHT_OUTPUT_BITWIDTH_BITS   0x0000000f
#define AUDIO_OUT_SDMCTL_RIGHT_OUTPUT_BITWIDTH_MSB    3
#define AUDIO_OUT_SDMCTL_RIGHT_OUTPUT_BITWIDTH_LSB    0
#define AUDIO_OUT_SDMCTL_RIGHT_OUTPUT_BITWIDTH_ACCESS "RW"
// =============================================================================
// Register    : AUDIO_OUT_QCLAMP_LEFT
// JTAG access : synchronous
// Description : Left channel quantisation clamp
#define AUDIO_OUT_QCLAMP_LEFT_OFFSET 0x0000000c
#define AUDIO_OUT_QCLAMP_LEFT_BITS   0xffffffff
#define AUDIO_OUT_QCLAMP_LEFT_RESET  0x00000000
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_QCLAMP_LEFT_MAX
// Description : Clamp to max s16 value prior to quantisation
#define AUDIO_OUT_QCLAMP_LEFT_MAX_RESET  0x0000
#define AUDIO_OUT_QCLAMP_LEFT_MAX_BITS   0xffff0000
#define AUDIO_OUT_QCLAMP_LEFT_MAX_MSB    31
#define AUDIO_OUT_QCLAMP_LEFT_MAX_LSB    16
#define AUDIO_OUT_QCLAMP_LEFT_MAX_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_QCLAMP_LEFT_MIN
// Description : Clamp to min s16 value prior to quantisation
#define AUDIO_OUT_QCLAMP_LEFT_MIN_RESET  0x0000
#define AUDIO_OUT_QCLAMP_LEFT_MIN_BITS   0x0000ffff
#define AUDIO_OUT_QCLAMP_LEFT_MIN_MSB    15
#define AUDIO_OUT_QCLAMP_LEFT_MIN_LSB    0
#define AUDIO_OUT_QCLAMP_LEFT_MIN_ACCESS "RW"
// =============================================================================
// Register    : AUDIO_OUT_QCLAMP_RIGHT
// JTAG access : synchronous
// Description : Right channel quantisation clamp
#define AUDIO_OUT_QCLAMP_RIGHT_OFFSET 0x00000010
#define AUDIO_OUT_QCLAMP_RIGHT_BITS   0xffffffff
#define AUDIO_OUT_QCLAMP_RIGHT_RESET  0x00000000
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_QCLAMP_RIGHT_MAX
// Description : Clamp to max s16 value prior to quantisation
#define AUDIO_OUT_QCLAMP_RIGHT_MAX_RESET  0x0000
#define AUDIO_OUT_QCLAMP_RIGHT_MAX_BITS   0xffff0000
#define AUDIO_OUT_QCLAMP_RIGHT_MAX_MSB    31
#define AUDIO_OUT_QCLAMP_RIGHT_MAX_LSB    16
#define AUDIO_OUT_QCLAMP_RIGHT_MAX_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_QCLAMP_RIGHT_MIN
// Description : Clamp to min s16 value prior to quantisation
#define AUDIO_OUT_QCLAMP_RIGHT_MIN_RESET  0x0000
#define AUDIO_OUT_QCLAMP_RIGHT_MIN_BITS   0x0000ffff
#define AUDIO_OUT_QCLAMP_RIGHT_MIN_MSB    15
#define AUDIO_OUT_QCLAMP_RIGHT_MIN_LSB    0
#define AUDIO_OUT_QCLAMP_RIGHT_MIN_ACCESS "RW"
// =============================================================================
// Register    : AUDIO_OUT_MUTE_CTRL_LEFT
// JTAG access : synchronous
// Description : Left channel mute/unmute de-pop
#define AUDIO_OUT_MUTE_CTRL_LEFT_OFFSET 0x00000014
#define AUDIO_OUT_MUTE_CTRL_LEFT_BITS   0x80ffff3f
#define AUDIO_OUT_MUTE_CTRL_LEFT_RESET  0x00010100
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_MUTE_CTRL_LEFT_BYPASS
// Description : 1 - Remove mute_ctrl from the left channel signal flow
//               0 - Normal operation
#define AUDIO_OUT_MUTE_CTRL_LEFT_BYPASS_RESET  0x0
#define AUDIO_OUT_MUTE_CTRL_LEFT_BYPASS_BITS   0x80000000
#define AUDIO_OUT_MUTE_CTRL_LEFT_BYPASS_MSB    31
#define AUDIO_OUT_MUTE_CTRL_LEFT_BYPASS_LSB    31
#define AUDIO_OUT_MUTE_CTRL_LEFT_BYPASS_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_MUTE_CTRL_LEFT_MUTE_PERIOD
// Description : Muting period control. The current ramp value is held constant
//               for mute_period sample times. At nominal settings, a value of
//               14
//               will produce a ~250ms ramp.
#define AUDIO_OUT_MUTE_CTRL_LEFT_MUTE_PERIOD_RESET  0x01
#define AUDIO_OUT_MUTE_CTRL_LEFT_MUTE_PERIOD_BITS   0x00ff0000
#define AUDIO_OUT_MUTE_CTRL_LEFT_MUTE_PERIOD_MSB    23
#define AUDIO_OUT_MUTE_CTRL_LEFT_MUTE_PERIOD_LSB    16
#define AUDIO_OUT_MUTE_CTRL_LEFT_MUTE_PERIOD_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_MUTE_CTRL_LEFT_STEP_SIZE
// Description : Muting incremental sample step size
#define AUDIO_OUT_MUTE_CTRL_LEFT_STEP_SIZE_RESET  0x01
#define AUDIO_OUT_MUTE_CTRL_LEFT_STEP_SIZE_BITS   0x0000ff00
#define AUDIO_OUT_MUTE_CTRL_LEFT_STEP_SIZE_MSB    15
#define AUDIO_OUT_MUTE_CTRL_LEFT_STEP_SIZE_LSB    8
#define AUDIO_OUT_MUTE_CTRL_LEFT_STEP_SIZE_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_MUTE_CTRL_LEFT_INIT_UNMUTE
// Description : Write 1 - initiate an unmute cycle if the mute_fsm is idle
//               Clear this bit when the FSM indicates unmute is complete.
#define AUDIO_OUT_MUTE_CTRL_LEFT_INIT_UNMUTE_RESET  0x0
#define AUDIO_OUT_MUTE_CTRL_LEFT_INIT_UNMUTE_BITS   0x00000020
#define AUDIO_OUT_MUTE_CTRL_LEFT_INIT_UNMUTE_MSB    5
#define AUDIO_OUT_MUTE_CTRL_LEFT_INIT_UNMUTE_LSB    5
#define AUDIO_OUT_MUTE_CTRL_LEFT_INIT_UNMUTE_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_MUTE_CTRL_LEFT_INIT_MUTE
// Description : Write 1 - initiate a mute cycle if mute_fsm is idle
//               Clear this bit when the FSM indicates unmute is complete.
#define AUDIO_OUT_MUTE_CTRL_LEFT_INIT_MUTE_RESET  0x0
#define AUDIO_OUT_MUTE_CTRL_LEFT_INIT_MUTE_BITS   0x00000010
#define AUDIO_OUT_MUTE_CTRL_LEFT_INIT_MUTE_MSB    4
#define AUDIO_OUT_MUTE_CTRL_LEFT_INIT_MUTE_LSB    4
#define AUDIO_OUT_MUTE_CTRL_LEFT_INIT_MUTE_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_MUTE_CTRL_LEFT_MUTE_FSM
// Description : Read-only status bits for the internal FSM.
//               0 - FSM idle, muted
//               1 - FSM in mute -> unmute transition
//               2 - FSM is idle (unmuted)
//               4 - FSM in unmuted -> mute transition
#define AUDIO_OUT_MUTE_CTRL_LEFT_MUTE_FSM_RESET  0x0
#define AUDIO_OUT_MUTE_CTRL_LEFT_MUTE_FSM_BITS   0x0000000f
#define AUDIO_OUT_MUTE_CTRL_LEFT_MUTE_FSM_MSB    3
#define AUDIO_OUT_MUTE_CTRL_LEFT_MUTE_FSM_LSB    0
#define AUDIO_OUT_MUTE_CTRL_LEFT_MUTE_FSM_ACCESS "RO"
// =============================================================================
// Register    : AUDIO_OUT_MUTE_CTRL_RIGHT
// JTAG access : synchronous
// Description : Right channel mute/unmute de-pop
#define AUDIO_OUT_MUTE_CTRL_RIGHT_OFFSET 0x00000018
#define AUDIO_OUT_MUTE_CTRL_RIGHT_BITS   0x80ffff3f
#define AUDIO_OUT_MUTE_CTRL_RIGHT_RESET  0x00010100
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_MUTE_CTRL_RIGHT_BYPASS
// Description : 1 - Remove mute_ctrl from the left channel signal flow
//               0 - Normal operation
#define AUDIO_OUT_MUTE_CTRL_RIGHT_BYPASS_RESET  0x0
#define AUDIO_OUT_MUTE_CTRL_RIGHT_BYPASS_BITS   0x80000000
#define AUDIO_OUT_MUTE_CTRL_RIGHT_BYPASS_MSB    31
#define AUDIO_OUT_MUTE_CTRL_RIGHT_BYPASS_LSB    31
#define AUDIO_OUT_MUTE_CTRL_RIGHT_BYPASS_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_MUTE_CTRL_RIGHT_MUTE_PERIOD
// Description : Muting period control. The current ramp value is held constant
//               for mute_period sample times. At nominal settings, a value of
//               14
//               will produce a ~250ms ramp.
#define AUDIO_OUT_MUTE_CTRL_RIGHT_MUTE_PERIOD_RESET  0x01
#define AUDIO_OUT_MUTE_CTRL_RIGHT_MUTE_PERIOD_BITS   0x00ff0000
#define AUDIO_OUT_MUTE_CTRL_RIGHT_MUTE_PERIOD_MSB    23
#define AUDIO_OUT_MUTE_CTRL_RIGHT_MUTE_PERIOD_LSB    16
#define AUDIO_OUT_MUTE_CTRL_RIGHT_MUTE_PERIOD_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_MUTE_CTRL_RIGHT_STEP_SIZE
// Description : Muting incremental sample step size
#define AUDIO_OUT_MUTE_CTRL_RIGHT_STEP_SIZE_RESET  0x01
#define AUDIO_OUT_MUTE_CTRL_RIGHT_STEP_SIZE_BITS   0x0000ff00
#define AUDIO_OUT_MUTE_CTRL_RIGHT_STEP_SIZE_MSB    15
#define AUDIO_OUT_MUTE_CTRL_RIGHT_STEP_SIZE_LSB    8
#define AUDIO_OUT_MUTE_CTRL_RIGHT_STEP_SIZE_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_MUTE_CTRL_RIGHT_INIT_UNMUTE
// Description : Write 1 - initiate an unmute cycle if the mute_fsm is idle
//               Clear this bit when the FSM indicates unmute is complete.
#define AUDIO_OUT_MUTE_CTRL_RIGHT_INIT_UNMUTE_RESET  0x0
#define AUDIO_OUT_MUTE_CTRL_RIGHT_INIT_UNMUTE_BITS   0x00000020
#define AUDIO_OUT_MUTE_CTRL_RIGHT_INIT_UNMUTE_MSB    5
#define AUDIO_OUT_MUTE_CTRL_RIGHT_INIT_UNMUTE_LSB    5
#define AUDIO_OUT_MUTE_CTRL_RIGHT_INIT_UNMUTE_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_MUTE_CTRL_RIGHT_INIT_MUTE
// Description : Write 1 - initiate a mute cycle if mute_fsm is idle
//               Clear this bit when the FSM indicates unmute is complete.
#define AUDIO_OUT_MUTE_CTRL_RIGHT_INIT_MUTE_RESET  0x0
#define AUDIO_OUT_MUTE_CTRL_RIGHT_INIT_MUTE_BITS   0x00000010
#define AUDIO_OUT_MUTE_CTRL_RIGHT_INIT_MUTE_MSB    4
#define AUDIO_OUT_MUTE_CTRL_RIGHT_INIT_MUTE_LSB    4
#define AUDIO_OUT_MUTE_CTRL_RIGHT_INIT_MUTE_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_MUTE_CTRL_RIGHT_MUTE_FSM
// Description : Read-only status bits for the internal FSM.
//               0 - FSM idle, muted
//               1 - FSM in mute -> unmute transition
//               2 - FSM is idle (unmuted)
//               4 - FSM in unmuted -> mute transition
#define AUDIO_OUT_MUTE_CTRL_RIGHT_MUTE_FSM_RESET  0x0
#define AUDIO_OUT_MUTE_CTRL_RIGHT_MUTE_FSM_BITS   0x0000000f
#define AUDIO_OUT_MUTE_CTRL_RIGHT_MUTE_FSM_MSB    3
#define AUDIO_OUT_MUTE_CTRL_RIGHT_MUTE_FSM_LSB    0
#define AUDIO_OUT_MUTE_CTRL_RIGHT_MUTE_FSM_ACCESS "RO"
// =============================================================================
// Register    : AUDIO_OUT_PWMCTL_LEFT
// JTAG access : synchronous
// Description : Left PWM channel control
#define AUDIO_OUT_PWMCTL_LEFT_OFFSET 0x0000001c
#define AUDIO_OUT_PWMCTL_LEFT_BITS   0x00000007
#define AUDIO_OUT_PWMCTL_LEFT_RESET  0x00000000
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_PWMCTL_LEFT_USE_PWMDAT
// Description : 0 - Use output from audio engine
//               1 - Use PWMDAT register
#define AUDIO_OUT_PWMCTL_LEFT_USE_PWMDAT_RESET  0x0
#define AUDIO_OUT_PWMCTL_LEFT_USE_PWMDAT_BITS   0x00000004
#define AUDIO_OUT_PWMCTL_LEFT_USE_PWMDAT_MSB    2
#define AUDIO_OUT_PWMCTL_LEFT_USE_PWMDAT_LSB    2
#define AUDIO_OUT_PWMCTL_LEFT_USE_PWMDAT_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_PWMCTL_LEFT_MODE
// Description : 1 - Use left-aligned PWM pulses
//               0 - Use centre-aligned PWM pulses
#define AUDIO_OUT_PWMCTL_LEFT_MODE_RESET  0x0
#define AUDIO_OUT_PWMCTL_LEFT_MODE_BITS   0x00000002
#define AUDIO_OUT_PWMCTL_LEFT_MODE_MSB    1
#define AUDIO_OUT_PWMCTL_LEFT_MODE_LSB    1
#define AUDIO_OUT_PWMCTL_LEFT_MODE_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_PWMCTL_LEFT_INVERT
// Description : 1 - Output (1-D)% duty cycle
//               0 - Output D% duty cycle
#define AUDIO_OUT_PWMCTL_LEFT_INVERT_RESET  0x0
#define AUDIO_OUT_PWMCTL_LEFT_INVERT_BITS   0x00000001
#define AUDIO_OUT_PWMCTL_LEFT_INVERT_MSB    0
#define AUDIO_OUT_PWMCTL_LEFT_INVERT_LSB    0
#define AUDIO_OUT_PWMCTL_LEFT_INVERT_ACCESS "RW"
// =============================================================================
// Register    : AUDIO_OUT_PWMRANGE_LEFT
// JTAG access : synchronous
// Description : Left PWM channel cycle period count
#define AUDIO_OUT_PWMRANGE_LEFT_OFFSET 0x00000020
#define AUDIO_OUT_PWMRANGE_LEFT_BITS   0x0000ffff
#define AUDIO_OUT_PWMRANGE_LEFT_RESET  0x00000000
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_PWMRANGE_LEFT_RANGE
// Description : None
#define AUDIO_OUT_PWMRANGE_LEFT_RANGE_RESET  0x0000
#define AUDIO_OUT_PWMRANGE_LEFT_RANGE_BITS   0x0000ffff
#define AUDIO_OUT_PWMRANGE_LEFT_RANGE_MSB    15
#define AUDIO_OUT_PWMRANGE_LEFT_RANGE_LSB    0
#define AUDIO_OUT_PWMRANGE_LEFT_RANGE_ACCESS "RW"
// =============================================================================
// Register    : AUDIO_OUT_PWMDAT_LEFT
// JTAG access : synchronous
// Description : PWM duty cycle for the left PWM channel when not in audio mode
#define AUDIO_OUT_PWMDAT_LEFT_OFFSET 0x00000024
#define AUDIO_OUT_PWMDAT_LEFT_BITS   0x0000ffff
#define AUDIO_OUT_PWMDAT_LEFT_RESET  0x00000000
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_PWMDAT_LEFT_DUTY
// Description : 16-bit unsigned duty cycle register
#define AUDIO_OUT_PWMDAT_LEFT_DUTY_RESET  0x0000
#define AUDIO_OUT_PWMDAT_LEFT_DUTY_BITS   0x0000ffff
#define AUDIO_OUT_PWMDAT_LEFT_DUTY_MSB    15
#define AUDIO_OUT_PWMDAT_LEFT_DUTY_LSB    0
#define AUDIO_OUT_PWMDAT_LEFT_DUTY_ACCESS "RW"
// =============================================================================
// Register    : AUDIO_OUT_PWMCTL_RIGHT
// JTAG access : synchronous
// Description : Right PWM channel control
#define AUDIO_OUT_PWMCTL_RIGHT_OFFSET 0x00000028
#define AUDIO_OUT_PWMCTL_RIGHT_BITS   0x00000007
#define AUDIO_OUT_PWMCTL_RIGHT_RESET  0x00000000
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_PWMCTL_RIGHT_USE_PWMDAT
// Description : 0 - Use output from audio engine
//               1 - Use PWMDAT register
#define AUDIO_OUT_PWMCTL_RIGHT_USE_PWMDAT_RESET  0x0
#define AUDIO_OUT_PWMCTL_RIGHT_USE_PWMDAT_BITS   0x00000004
#define AUDIO_OUT_PWMCTL_RIGHT_USE_PWMDAT_MSB    2
#define AUDIO_OUT_PWMCTL_RIGHT_USE_PWMDAT_LSB    2
#define AUDIO_OUT_PWMCTL_RIGHT_USE_PWMDAT_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_PWMCTL_RIGHT_MODE
// Description : 1 - Use left-aligned PWM pulses
//               0 - Use centre-aligned PWM pulses
#define AUDIO_OUT_PWMCTL_RIGHT_MODE_RESET  0x0
#define AUDIO_OUT_PWMCTL_RIGHT_MODE_BITS   0x00000002
#define AUDIO_OUT_PWMCTL_RIGHT_MODE_MSB    1
#define AUDIO_OUT_PWMCTL_RIGHT_MODE_LSB    1
#define AUDIO_OUT_PWMCTL_RIGHT_MODE_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_PWMCTL_RIGHT_INVERT
// Description : 1 - Output (1-D)% duty cycle
//               0 - Output D% duty cycle
#define AUDIO_OUT_PWMCTL_RIGHT_INVERT_RESET  0x0
#define AUDIO_OUT_PWMCTL_RIGHT_INVERT_BITS   0x00000001
#define AUDIO_OUT_PWMCTL_RIGHT_INVERT_MSB    0
#define AUDIO_OUT_PWMCTL_RIGHT_INVERT_LSB    0
#define AUDIO_OUT_PWMCTL_RIGHT_INVERT_ACCESS "RW"
// =============================================================================
// Register    : AUDIO_OUT_PWMRANGE_RIGHT
// JTAG access : synchronous
// Description : Right PWM channel cycle period count
#define AUDIO_OUT_PWMRANGE_RIGHT_OFFSET 0x0000002c
#define AUDIO_OUT_PWMRANGE_RIGHT_BITS   0x0000ffff
#define AUDIO_OUT_PWMRANGE_RIGHT_RESET  0x00000000
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_PWMRANGE_RIGHT_RANGE
// Description : None
#define AUDIO_OUT_PWMRANGE_RIGHT_RANGE_RESET  0x0000
#define AUDIO_OUT_PWMRANGE_RIGHT_RANGE_BITS   0x0000ffff
#define AUDIO_OUT_PWMRANGE_RIGHT_RANGE_MSB    15
#define AUDIO_OUT_PWMRANGE_RIGHT_RANGE_LSB    0
#define AUDIO_OUT_PWMRANGE_RIGHT_RANGE_ACCESS "RW"
// =============================================================================
// Register    : AUDIO_OUT_PWMDAT_RIGHT
// JTAG access : synchronous
// Description : PWM duty cycle for the right PWM channel when not in audio mode
#define AUDIO_OUT_PWMDAT_RIGHT_OFFSET 0x00000030
#define AUDIO_OUT_PWMDAT_RIGHT_BITS   0x0000ffff
#define AUDIO_OUT_PWMDAT_RIGHT_RESET  0x00000000
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_PWMDAT_RIGHT_DUTY
// Description : 16-bit unsigned duty cycle register
#define AUDIO_OUT_PWMDAT_RIGHT_DUTY_RESET  0x0000
#define AUDIO_OUT_PWMDAT_RIGHT_DUTY_BITS   0x0000ffff
#define AUDIO_OUT_PWMDAT_RIGHT_DUTY_MSB    15
#define AUDIO_OUT_PWMDAT_RIGHT_DUTY_LSB    0
#define AUDIO_OUT_PWMDAT_RIGHT_DUTY_ACCESS "RW"
// =============================================================================
// Register    : AUDIO_OUT_FIFO_CONTROL
// JTAG access : synchronous
// Description : Level control for DMA dreq pacing and interrupt generation
#define AUDIO_OUT_FIFO_CONTROL_OFFSET 0x00000034
#define AUDIO_OUT_FIFO_CONTROL_BITS   0x831f3f3f
#define AUDIO_OUT_FIFO_CONTROL_RESET  0x00020010
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_FIFO_CONTROL_DMA_DREQ_EN
// Description : 1 - Assert DREQ to DMA when fewer than fifo_threshold spaces
//               are available
//               0 - Don't assert DREQ
#define AUDIO_OUT_FIFO_CONTROL_DMA_DREQ_EN_RESET  0x0
#define AUDIO_OUT_FIFO_CONTROL_DMA_DREQ_EN_BITS   0x80000000
#define AUDIO_OUT_FIFO_CONTROL_DMA_DREQ_EN_MSB    31
#define AUDIO_OUT_FIFO_CONTROL_DMA_DREQ_EN_LSB    31
#define AUDIO_OUT_FIFO_CONTROL_DMA_DREQ_EN_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_FIFO_CONTROL_FLUSH_DONE
// Description : None
#define AUDIO_OUT_FIFO_CONTROL_FLUSH_DONE_RESET  0x0
#define AUDIO_OUT_FIFO_CONTROL_FLUSH_DONE_BITS   0x02000000
#define AUDIO_OUT_FIFO_CONTROL_FLUSH_DONE_MSB    25
#define AUDIO_OUT_FIFO_CONTROL_FLUSH_DONE_LSB    25
#define AUDIO_OUT_FIFO_CONTROL_FLUSH_DONE_ACCESS "RO"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_FIFO_CONTROL_FIFO_FLUSH
// Description : Set to 1 to initiate a FIFO flush. Flushing should only be done
//               after disabling the peripheral, to reset the write side of the
//               FIFO.
//               Clear this bit when flush_done reads back as 1.
#define AUDIO_OUT_FIFO_CONTROL_FIFO_FLUSH_RESET  0x0
#define AUDIO_OUT_FIFO_CONTROL_FIFO_FLUSH_BITS   0x01000000
#define AUDIO_OUT_FIFO_CONTROL_FIFO_FLUSH_MSB    24
#define AUDIO_OUT_FIFO_CONTROL_FIFO_FLUSH_LSB    24
#define AUDIO_OUT_FIFO_CONTROL_FIFO_FLUSH_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_FIFO_CONTROL_DWELL_TIME
// Description : Delay in number of bus cycles before successive DREQs are
//               generated.
//               Used to account for system bus latency in write data arriving
//               at the FIFO.
#define AUDIO_OUT_FIFO_CONTROL_DWELL_TIME_RESET  0x02
#define AUDIO_OUT_FIFO_CONTROL_DWELL_TIME_BITS   0x001f0000
#define AUDIO_OUT_FIFO_CONTROL_DWELL_TIME_MSB    20
#define AUDIO_OUT_FIFO_CONTROL_DWELL_TIME_LSB    16
#define AUDIO_OUT_FIFO_CONTROL_DWELL_TIME_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_FIFO_CONTROL_FIFO_NUM_WORDS
// Description : Number of available spaces in the FIFO
#define AUDIO_OUT_FIFO_CONTROL_FIFO_NUM_WORDS_RESET  0x00
#define AUDIO_OUT_FIFO_CONTROL_FIFO_NUM_WORDS_BITS   0x00003f00
#define AUDIO_OUT_FIFO_CONTROL_FIFO_NUM_WORDS_MSB    13
#define AUDIO_OUT_FIFO_CONTROL_FIFO_NUM_WORDS_LSB    8
#define AUDIO_OUT_FIFO_CONTROL_FIFO_NUM_WORDS_ACCESS "RO"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_FIFO_CONTROL_FIFO_THRESHOLD
// Description : Threshold control. If there are fewer than N spaces in the
//               sample FIFO, DMA dreq and/or the interrupt line is asserted.
#define AUDIO_OUT_FIFO_CONTROL_FIFO_THRESHOLD_RESET  0x10
#define AUDIO_OUT_FIFO_CONTROL_FIFO_THRESHOLD_BITS   0x0000003f
#define AUDIO_OUT_FIFO_CONTROL_FIFO_THRESHOLD_MSB    5
#define AUDIO_OUT_FIFO_CONTROL_FIFO_THRESHOLD_LSB    0
#define AUDIO_OUT_FIFO_CONTROL_FIFO_THRESHOLD_ACCESS "RW"
// =============================================================================
// Register    : AUDIO_OUT_SAMPLE_FIFO
// JTAG access : synchronous
// Description : Sample FIFO. LSW is left-channel data, MSW is right-channel
//               data.
//               Write: write packed 16-bit data into FIFO. Reads are ignored.
#define AUDIO_OUT_SAMPLE_FIFO_OFFSET 0x00000038
#define AUDIO_OUT_SAMPLE_FIFO_BITS   0xffffffff
#define AUDIO_OUT_SAMPLE_FIFO_RESET  0x00000000
#define AUDIO_OUT_SAMPLE_FIFO_MSB    31
#define AUDIO_OUT_SAMPLE_FIFO_LSB    0
#define AUDIO_OUT_SAMPLE_FIFO_ACCESS "WF"
// =============================================================================
// Register    : AUDIO_OUT_INTR
// JTAG access : synchronous
// Description : Raw Interrupts
#define AUDIO_OUT_INTR_OFFSET 0x0000003c
#define AUDIO_OUT_INTR_BITS   0x0000007f
#define AUDIO_OUT_INTR_RESET  0x00000000
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTR_MUTE_R_DONE
// Description : None
#define AUDIO_OUT_INTR_MUTE_R_DONE_RESET  0x0
#define AUDIO_OUT_INTR_MUTE_R_DONE_BITS   0x00000040
#define AUDIO_OUT_INTR_MUTE_R_DONE_MSB    6
#define AUDIO_OUT_INTR_MUTE_R_DONE_LSB    6
#define AUDIO_OUT_INTR_MUTE_R_DONE_ACCESS "WC"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTR_MUTE_L_DONE
// Description : None
#define AUDIO_OUT_INTR_MUTE_L_DONE_RESET  0x0
#define AUDIO_OUT_INTR_MUTE_L_DONE_BITS   0x00000020
#define AUDIO_OUT_INTR_MUTE_L_DONE_MSB    5
#define AUDIO_OUT_INTR_MUTE_L_DONE_LSB    5
#define AUDIO_OUT_INTR_MUTE_L_DONE_ACCESS "WC"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTR_DREQ_ACTIVE
// Description : None
#define AUDIO_OUT_INTR_DREQ_ACTIVE_RESET  0x0
#define AUDIO_OUT_INTR_DREQ_ACTIVE_BITS   0x00000010
#define AUDIO_OUT_INTR_DREQ_ACTIVE_MSB    4
#define AUDIO_OUT_INTR_DREQ_ACTIVE_LSB    4
#define AUDIO_OUT_INTR_DREQ_ACTIVE_ACCESS "RO"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTR_FIFO_FULL
// Description : None
#define AUDIO_OUT_INTR_FIFO_FULL_RESET  0x0
#define AUDIO_OUT_INTR_FIFO_FULL_BITS   0x00000008
#define AUDIO_OUT_INTR_FIFO_FULL_MSB    3
#define AUDIO_OUT_INTR_FIFO_FULL_LSB    3
#define AUDIO_OUT_INTR_FIFO_FULL_ACCESS "RO"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTR_FIFO_EMPTY
// Description : None
#define AUDIO_OUT_INTR_FIFO_EMPTY_RESET  0x0
#define AUDIO_OUT_INTR_FIFO_EMPTY_BITS   0x00000004
#define AUDIO_OUT_INTR_FIFO_EMPTY_MSB    2
#define AUDIO_OUT_INTR_FIFO_EMPTY_LSB    2
#define AUDIO_OUT_INTR_FIFO_EMPTY_ACCESS "RO"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTR_FIFO_OVERFLOW
// Description : None
#define AUDIO_OUT_INTR_FIFO_OVERFLOW_RESET  0x0
#define AUDIO_OUT_INTR_FIFO_OVERFLOW_BITS   0x00000002
#define AUDIO_OUT_INTR_FIFO_OVERFLOW_MSB    1
#define AUDIO_OUT_INTR_FIFO_OVERFLOW_LSB    1
#define AUDIO_OUT_INTR_FIFO_OVERFLOW_ACCESS "WC"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTR_FIFO_UNDERFLOW
// Description : None
#define AUDIO_OUT_INTR_FIFO_UNDERFLOW_RESET  0x0
#define AUDIO_OUT_INTR_FIFO_UNDERFLOW_BITS   0x00000001
#define AUDIO_OUT_INTR_FIFO_UNDERFLOW_MSB    0
#define AUDIO_OUT_INTR_FIFO_UNDERFLOW_LSB    0
#define AUDIO_OUT_INTR_FIFO_UNDERFLOW_ACCESS "WC"
// =============================================================================
// Register    : AUDIO_OUT_INTE
// JTAG access : synchronous
// Description : Interrupt Enable
#define AUDIO_OUT_INTE_OFFSET 0x00000040
#define AUDIO_OUT_INTE_BITS   0x0000007f
#define AUDIO_OUT_INTE_RESET  0x00000000
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTE_MUTE_R_DONE
// Description : None
#define AUDIO_OUT_INTE_MUTE_R_DONE_RESET  0x0
#define AUDIO_OUT_INTE_MUTE_R_DONE_BITS   0x00000040
#define AUDIO_OUT_INTE_MUTE_R_DONE_MSB    6
#define AUDIO_OUT_INTE_MUTE_R_DONE_LSB    6
#define AUDIO_OUT_INTE_MUTE_R_DONE_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTE_MUTE_L_DONE
// Description : None
#define AUDIO_OUT_INTE_MUTE_L_DONE_RESET  0x0
#define AUDIO_OUT_INTE_MUTE_L_DONE_BITS   0x00000020
#define AUDIO_OUT_INTE_MUTE_L_DONE_MSB    5
#define AUDIO_OUT_INTE_MUTE_L_DONE_LSB    5
#define AUDIO_OUT_INTE_MUTE_L_DONE_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTE_DREQ_ACTIVE
// Description : None
#define AUDIO_OUT_INTE_DREQ_ACTIVE_RESET  0x0
#define AUDIO_OUT_INTE_DREQ_ACTIVE_BITS   0x00000010
#define AUDIO_OUT_INTE_DREQ_ACTIVE_MSB    4
#define AUDIO_OUT_INTE_DREQ_ACTIVE_LSB    4
#define AUDIO_OUT_INTE_DREQ_ACTIVE_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTE_FIFO_FULL
// Description : None
#define AUDIO_OUT_INTE_FIFO_FULL_RESET  0x0
#define AUDIO_OUT_INTE_FIFO_FULL_BITS   0x00000008
#define AUDIO_OUT_INTE_FIFO_FULL_MSB    3
#define AUDIO_OUT_INTE_FIFO_FULL_LSB    3
#define AUDIO_OUT_INTE_FIFO_FULL_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTE_FIFO_EMPTY
// Description : None
#define AUDIO_OUT_INTE_FIFO_EMPTY_RESET  0x0
#define AUDIO_OUT_INTE_FIFO_EMPTY_BITS   0x00000004
#define AUDIO_OUT_INTE_FIFO_EMPTY_MSB    2
#define AUDIO_OUT_INTE_FIFO_EMPTY_LSB    2
#define AUDIO_OUT_INTE_FIFO_EMPTY_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTE_FIFO_OVERFLOW
// Description : None
#define AUDIO_OUT_INTE_FIFO_OVERFLOW_RESET  0x0
#define AUDIO_OUT_INTE_FIFO_OVERFLOW_BITS   0x00000002
#define AUDIO_OUT_INTE_FIFO_OVERFLOW_MSB    1
#define AUDIO_OUT_INTE_FIFO_OVERFLOW_LSB    1
#define AUDIO_OUT_INTE_FIFO_OVERFLOW_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTE_FIFO_UNDERFLOW
// Description : None
#define AUDIO_OUT_INTE_FIFO_UNDERFLOW_RESET  0x0
#define AUDIO_OUT_INTE_FIFO_UNDERFLOW_BITS   0x00000001
#define AUDIO_OUT_INTE_FIFO_UNDERFLOW_MSB    0
#define AUDIO_OUT_INTE_FIFO_UNDERFLOW_LSB    0
#define AUDIO_OUT_INTE_FIFO_UNDERFLOW_ACCESS "RW"
// =============================================================================
// Register    : AUDIO_OUT_INTF
// JTAG access : synchronous
// Description : Interrupt Force
#define AUDIO_OUT_INTF_OFFSET 0x00000044
#define AUDIO_OUT_INTF_BITS   0x0000007f
#define AUDIO_OUT_INTF_RESET  0x00000000
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTF_MUTE_R_DONE
// Description : None
#define AUDIO_OUT_INTF_MUTE_R_DONE_RESET  0x0
#define AUDIO_OUT_INTF_MUTE_R_DONE_BITS   0x00000040
#define AUDIO_OUT_INTF_MUTE_R_DONE_MSB    6
#define AUDIO_OUT_INTF_MUTE_R_DONE_LSB    6
#define AUDIO_OUT_INTF_MUTE_R_DONE_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTF_MUTE_L_DONE
// Description : None
#define AUDIO_OUT_INTF_MUTE_L_DONE_RESET  0x0
#define AUDIO_OUT_INTF_MUTE_L_DONE_BITS   0x00000020
#define AUDIO_OUT_INTF_MUTE_L_DONE_MSB    5
#define AUDIO_OUT_INTF_MUTE_L_DONE_LSB    5
#define AUDIO_OUT_INTF_MUTE_L_DONE_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTF_DREQ_ACTIVE
// Description : None
#define AUDIO_OUT_INTF_DREQ_ACTIVE_RESET  0x0
#define AUDIO_OUT_INTF_DREQ_ACTIVE_BITS   0x00000010
#define AUDIO_OUT_INTF_DREQ_ACTIVE_MSB    4
#define AUDIO_OUT_INTF_DREQ_ACTIVE_LSB    4
#define AUDIO_OUT_INTF_DREQ_ACTIVE_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTF_FIFO_FULL
// Description : None
#define AUDIO_OUT_INTF_FIFO_FULL_RESET  0x0
#define AUDIO_OUT_INTF_FIFO_FULL_BITS   0x00000008
#define AUDIO_OUT_INTF_FIFO_FULL_MSB    3
#define AUDIO_OUT_INTF_FIFO_FULL_LSB    3
#define AUDIO_OUT_INTF_FIFO_FULL_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTF_FIFO_EMPTY
// Description : None
#define AUDIO_OUT_INTF_FIFO_EMPTY_RESET  0x0
#define AUDIO_OUT_INTF_FIFO_EMPTY_BITS   0x00000004
#define AUDIO_OUT_INTF_FIFO_EMPTY_MSB    2
#define AUDIO_OUT_INTF_FIFO_EMPTY_LSB    2
#define AUDIO_OUT_INTF_FIFO_EMPTY_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTF_FIFO_OVERFLOW
// Description : None
#define AUDIO_OUT_INTF_FIFO_OVERFLOW_RESET  0x0
#define AUDIO_OUT_INTF_FIFO_OVERFLOW_BITS   0x00000002
#define AUDIO_OUT_INTF_FIFO_OVERFLOW_MSB    1
#define AUDIO_OUT_INTF_FIFO_OVERFLOW_LSB    1
#define AUDIO_OUT_INTF_FIFO_OVERFLOW_ACCESS "RW"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTF_FIFO_UNDERFLOW
// Description : None
#define AUDIO_OUT_INTF_FIFO_UNDERFLOW_RESET  0x0
#define AUDIO_OUT_INTF_FIFO_UNDERFLOW_BITS   0x00000001
#define AUDIO_OUT_INTF_FIFO_UNDERFLOW_MSB    0
#define AUDIO_OUT_INTF_FIFO_UNDERFLOW_LSB    0
#define AUDIO_OUT_INTF_FIFO_UNDERFLOW_ACCESS "RW"
// =============================================================================
// Register    : AUDIO_OUT_INTS
// JTAG access : synchronous
// Description : Interrupt status after masking & forcing
#define AUDIO_OUT_INTS_OFFSET 0x00000048
#define AUDIO_OUT_INTS_BITS   0x0000007f
#define AUDIO_OUT_INTS_RESET  0x00000000
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTS_MUTE_R_DONE
// Description : None
#define AUDIO_OUT_INTS_MUTE_R_DONE_RESET  0x0
#define AUDIO_OUT_INTS_MUTE_R_DONE_BITS   0x00000040
#define AUDIO_OUT_INTS_MUTE_R_DONE_MSB    6
#define AUDIO_OUT_INTS_MUTE_R_DONE_LSB    6
#define AUDIO_OUT_INTS_MUTE_R_DONE_ACCESS "RO"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTS_MUTE_L_DONE
// Description : None
#define AUDIO_OUT_INTS_MUTE_L_DONE_RESET  0x0
#define AUDIO_OUT_INTS_MUTE_L_DONE_BITS   0x00000020
#define AUDIO_OUT_INTS_MUTE_L_DONE_MSB    5
#define AUDIO_OUT_INTS_MUTE_L_DONE_LSB    5
#define AUDIO_OUT_INTS_MUTE_L_DONE_ACCESS "RO"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTS_DREQ_ACTIVE
// Description : None
#define AUDIO_OUT_INTS_DREQ_ACTIVE_RESET  0x0
#define AUDIO_OUT_INTS_DREQ_ACTIVE_BITS   0x00000010
#define AUDIO_OUT_INTS_DREQ_ACTIVE_MSB    4
#define AUDIO_OUT_INTS_DREQ_ACTIVE_LSB    4
#define AUDIO_OUT_INTS_DREQ_ACTIVE_ACCESS "RO"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTS_FIFO_FULL
// Description : None
#define AUDIO_OUT_INTS_FIFO_FULL_RESET  0x0
#define AUDIO_OUT_INTS_FIFO_FULL_BITS   0x00000008
#define AUDIO_OUT_INTS_FIFO_FULL_MSB    3
#define AUDIO_OUT_INTS_FIFO_FULL_LSB    3
#define AUDIO_OUT_INTS_FIFO_FULL_ACCESS "RO"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTS_FIFO_EMPTY
// Description : None
#define AUDIO_OUT_INTS_FIFO_EMPTY_RESET  0x0
#define AUDIO_OUT_INTS_FIFO_EMPTY_BITS   0x00000004
#define AUDIO_OUT_INTS_FIFO_EMPTY_MSB    2
#define AUDIO_OUT_INTS_FIFO_EMPTY_LSB    2
#define AUDIO_OUT_INTS_FIFO_EMPTY_ACCESS "RO"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTS_FIFO_OVERFLOW
// Description : None
#define AUDIO_OUT_INTS_FIFO_OVERFLOW_RESET  0x0
#define AUDIO_OUT_INTS_FIFO_OVERFLOW_BITS   0x00000002
#define AUDIO_OUT_INTS_FIFO_OVERFLOW_MSB    1
#define AUDIO_OUT_INTS_FIFO_OVERFLOW_LSB    1
#define AUDIO_OUT_INTS_FIFO_OVERFLOW_ACCESS "RO"
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_INTS_FIFO_UNDERFLOW
// Description : None
#define AUDIO_OUT_INTS_FIFO_UNDERFLOW_RESET  0x0
#define AUDIO_OUT_INTS_FIFO_UNDERFLOW_BITS   0x00000001
#define AUDIO_OUT_INTS_FIFO_UNDERFLOW_MSB    0
#define AUDIO_OUT_INTS_FIFO_UNDERFLOW_LSB    0
#define AUDIO_OUT_INTS_FIFO_UNDERFLOW_ACCESS "RO"
// =============================================================================
// Register    : AUDIO_OUT_BLOCK_ID
// JTAG access : synchronous
// Description : Block Identifier
//               Hexadecimal representation of "AUDO"
#define AUDIO_OUT_BLOCK_ID_OFFSET 0x0000004c
#define AUDIO_OUT_BLOCK_ID_BITS   0xffffffff
#define AUDIO_OUT_BLOCK_ID_RESET  0x4155444f
#define AUDIO_OUT_BLOCK_ID_MSB    31
#define AUDIO_OUT_BLOCK_ID_LSB    0
#define AUDIO_OUT_BLOCK_ID_ACCESS "RO"
// =============================================================================
// Register    : AUDIO_OUT_INSTANCE_ID
// JTAG access : synchronous
// Description : Block Instance Identifier
#define AUDIO_OUT_INSTANCE_ID_OFFSET 0x00000050
#define AUDIO_OUT_INSTANCE_ID_BITS   0x0000000f
#define AUDIO_OUT_INSTANCE_ID_RESET  0x00000000
#define AUDIO_OUT_INSTANCE_ID_MSB    3
#define AUDIO_OUT_INSTANCE_ID_LSB    0
#define AUDIO_OUT_INSTANCE_ID_ACCESS "RO"
// =============================================================================
// Register    : AUDIO_OUT_RSTSEQ_AUTO
// JTAG access : synchronous
// Description : None
#define AUDIO_OUT_RSTSEQ_AUTO_OFFSET 0x00000054
#define AUDIO_OUT_RSTSEQ_AUTO_BITS   0x00000001
#define AUDIO_OUT_RSTSEQ_AUTO_RESET  0x00000001
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_RSTSEQ_AUTO_BUSADAPTER
// Description : 1 = reset is controlled by the sequencer
//               0 = reset is controlled by rstseq_ctrl
#define AUDIO_OUT_RSTSEQ_AUTO_BUSADAPTER_RESET  0x1
#define AUDIO_OUT_RSTSEQ_AUTO_BUSADAPTER_BITS   0x00000001
#define AUDIO_OUT_RSTSEQ_AUTO_BUSADAPTER_MSB    0
#define AUDIO_OUT_RSTSEQ_AUTO_BUSADAPTER_LSB    0
#define AUDIO_OUT_RSTSEQ_AUTO_BUSADAPTER_ACCESS "RW"
// =============================================================================
// Register    : AUDIO_OUT_RSTSEQ_PARALLEL
// JTAG access : synchronous
// Description : None
#define AUDIO_OUT_RSTSEQ_PARALLEL_OFFSET 0x00000058
#define AUDIO_OUT_RSTSEQ_PARALLEL_BITS   0x00000001
#define AUDIO_OUT_RSTSEQ_PARALLEL_RESET  0x00000000
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_RSTSEQ_PARALLEL_BUSADAPTER
// Description : Is this reset parallel (i.e. not part of the sequence)
#define AUDIO_OUT_RSTSEQ_PARALLEL_BUSADAPTER_RESET  0x0
#define AUDIO_OUT_RSTSEQ_PARALLEL_BUSADAPTER_BITS   0x00000001
#define AUDIO_OUT_RSTSEQ_PARALLEL_BUSADAPTER_MSB    0
#define AUDIO_OUT_RSTSEQ_PARALLEL_BUSADAPTER_LSB    0
#define AUDIO_OUT_RSTSEQ_PARALLEL_BUSADAPTER_ACCESS "RO"
// =============================================================================
// Register    : AUDIO_OUT_RSTSEQ_CTRL
// JTAG access : synchronous
// Description : None
#define AUDIO_OUT_RSTSEQ_CTRL_OFFSET 0x0000005c
#define AUDIO_OUT_RSTSEQ_CTRL_BITS   0x00000001
#define AUDIO_OUT_RSTSEQ_CTRL_RESET  0x00000000
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_RSTSEQ_CTRL_BUSADAPTER
// Description : 1 = keep the reset asserted
//               0 = keep the reset deasserted
//               This is ignored if rstseq_auto=1
#define AUDIO_OUT_RSTSEQ_CTRL_BUSADAPTER_RESET  0x0
#define AUDIO_OUT_RSTSEQ_CTRL_BUSADAPTER_BITS   0x00000001
#define AUDIO_OUT_RSTSEQ_CTRL_BUSADAPTER_MSB    0
#define AUDIO_OUT_RSTSEQ_CTRL_BUSADAPTER_LSB    0
#define AUDIO_OUT_RSTSEQ_CTRL_BUSADAPTER_ACCESS "RW"
// =============================================================================
// Register    : AUDIO_OUT_RSTSEQ_TRIG
// JTAG access : synchronous
// Description : None
#define AUDIO_OUT_RSTSEQ_TRIG_OFFSET 0x00000060
#define AUDIO_OUT_RSTSEQ_TRIG_BITS   0x00000001
#define AUDIO_OUT_RSTSEQ_TRIG_RESET  0x00000000
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_RSTSEQ_TRIG_BUSADAPTER
// Description : Pulses the reset output
#define AUDIO_OUT_RSTSEQ_TRIG_BUSADAPTER_RESET  0x0
#define AUDIO_OUT_RSTSEQ_TRIG_BUSADAPTER_BITS   0x00000001
#define AUDIO_OUT_RSTSEQ_TRIG_BUSADAPTER_MSB    0
#define AUDIO_OUT_RSTSEQ_TRIG_BUSADAPTER_LSB    0
#define AUDIO_OUT_RSTSEQ_TRIG_BUSADAPTER_ACCESS "SC"
// =============================================================================
// Register    : AUDIO_OUT_RSTSEQ_DONE
// JTAG access : synchronous
// Description : None
#define AUDIO_OUT_RSTSEQ_DONE_OFFSET 0x00000064
#define AUDIO_OUT_RSTSEQ_DONE_BITS   0x00000001
#define AUDIO_OUT_RSTSEQ_DONE_RESET  0x00000000
// -----------------------------------------------------------------------------
// Field       : AUDIO_OUT_RSTSEQ_DONE_BUSADAPTER
// Description : Indicates the current state of the reset
#define AUDIO_OUT_RSTSEQ_DONE_BUSADAPTER_RESET  0x0
#define AUDIO_OUT_RSTSEQ_DONE_BUSADAPTER_BITS   0x00000001
#define AUDIO_OUT_RSTSEQ_DONE_BUSADAPTER_MSB    0
#define AUDIO_OUT_RSTSEQ_DONE_BUSADAPTER_LSB    0
#define AUDIO_OUT_RSTSEQ_DONE_BUSADAPTER_ACCESS "RO"
// =============================================================================
#endif // AUDIO_OUT_REGS_DEFINED
